import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Providers } from '@/lib/providers';
import Header from './components/Header';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';

config.autoAddCss = false;

const poppins = Poppins({ subsets: ['latin'], weight: ['300', '500', '700'] });

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body className={poppins.className}>
          <Header title="My Portfolio" />
          {children}
        </body>
      </html>
    </Providers>
  );
}
