version: '3.8'

services:
  app:
    build: .
    container_name: michellerogers
    restart: unless-stopped
    environment:
      - MONGO_URI=
      - SENDGRID_API_KEY=
      - PROJECT_ID=
      - KEYFILE_NAME=
      - BUCKET=
      - STORAGE_URL=
      - JWT_SECRET=
    ports:
      - 5000:5000
